### ISSUE TITLE
AWS Kinesis Firehose limit exceeded in haystack-pipes/firehose-writer

### ISSUE THREAD

**Issue by jeffbakerexpedia** [ExpediaDotCom/haystack-pipes#251]
Message from log:
01 Oct 2018 18:22:28.023 ERROR [pool-4-thread-11] com.expedia.www.haystack.pipes.firehoseWriter.S3Sender Unexpected exception received from AWS Firehose, will retry all records com.amazonaws.services.kinesisfirehose.model.AmazonKinesisFirehoseException: 1 validation error detected: Value 'java.nio.HeapByteBuffer[pos=0 lim=1024216 cap=1024216]' at 'records.1.member.data' failed to satisfy constraint: Member must have length less than or equal to 1024000 (Service: AmazonKinesisFirehose; Status Code: 400; Error Code: ValidationException; Request ID: be669c5d-d4b8-452d-b505-79cc1a952048)\n	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)\n	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)\n	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)\n	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)\n	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)\n	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)\n	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)\n	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)\n	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)\n	at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.doInvoke(AmazonKinesisFirehoseClient.java:1105)\n	at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.invoke(AmazonKinesisFirehoseClient.java:1081)\n	at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.executePutRecordBatch(AmazonKinesisFirehoseClient.java:825)\n	at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseAsyncClient$7.call(AmazonKinesisFirehoseAsyncClient.java:464)\n	at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseAsyncClient$7.call(AmazonKinesisFirehoseAsyncClient.java:458)\n	at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n	at java.lang.Thread.run(Thread.java:748)\n kubernetes.container_name:pipes-firehose-writer kubernetes.pod_name:pipes-firehose-writer-7bf8467f4b-79qks kubernetes.labels.k8s-app:pipes-firehose-writer tag:kubernetes.var.log.containers.pipes-firehose-writer-7bf8467f4b-79qks_haystack-apps_pipes-firehose-writer-7d57817a099b41431cb2d690389e7358a31fce535d4b7f1e97034eece852b377.log stream:stdout docker.container_id:7d57817a099b41431cb2d690389e7358a31fce535d4b7f1e97034eece852b377 kubernetes.namespace_name:haystack-apps kubernetes.pod_id:4d87c5b0-c0e5-11e8-a14a-0a9d14b5ed84 kubernetes.labels.pod-template-hash:3694023906 kubernetes.host:ip-10-1-235-92.us-west-2.compute.internal kubernetes.master_url:https://100.64.0.1:443/api @timestamp:October 1st 2018, 11:22:28.000 _id:AWYw3hZEqMZZHYg8CQQB _type:fluentd _index:logstash-2018.10.01 _score: -

**Comment by jeffbakerexpedia** [comment]
This issue was only seen once, and so far I have not been able to recreate it in a new unit test. (I will commit that new unit test to the repository.) One rather ugly fix would be to catch the exception and handle it by splitting the record into multiple records; this fix does have an edge case where each of the four 1 MB records exceeds the limit meaning that the request must be split into two requests. But at any rate it's an ugly fix that makes it clear we don't yet understand the root cause.

**Comment by jeffbakerexpedia** [comment]
Error happened again. Since Pipes has been running for many months without seeing this issue, and now we've seen it twice in a week, or theory is that the data itself is expanding as it goes from a StringBuilder into a String into a byte array. Initial fix will be to just decrease the maximum record size (the first time this error occurred it was 1024216-1024000 = 216 bytes too big; this second time it was 1025474-1024000 = 1474 bytes too big, so decreasing the current limit in code from 1,000,000 to 999,000 has very little impact on cost an performance but will minimize the chance of occurrence. This change will also be accompanied by a log of the offending byte array which unfortunately is a very large structure but may provide some more information about root cause. The long term fix will involve using a byte array instead of a StringBuilder to store the spans; this fix also creates less garbage than the current StringBuilder implementation.

**Comment by jeffbakerexpedia** [comment]
It's very clear that the FirehoseStringBufferCollector class's use of StringBuilder to aggregate before the record gets big enough is the problem; if any non-ASCII characters are in the message, they risk encoding to more than one byte. The fix is to use a byte array directly.

**Comment by jeffbakerexpedia** [comment]
This issue has been fixed with https://github.com/ExpediaDotCom/haystack-pipes/pull/255 and https://github.com/ExpediaDotCom/haystack-pipes/pull/256. (The latter CLN simply changed constants to correctly reflect AWS Kinesis Firehose requirements.)
